import type { Course } from './types';

export const courses: Course[] = [
  {
    id: '1',
    title: 'Introduction to Constitutional Law',
    description: 'A foundational course on the principles of constitutional law.',
    longDescription: 'Dive deep into the framework of the Indian Constitution. This course covers the fundamental rights, directive principles, and the structure of the Indian government. Ideal for beginners and law aspirants.',
    instructor: 'Dr. Ananya Sharma',
    price: 499,
    originalPrice: 999,
    rating: 4.8,
    reviews: 1250,
    duration: '12 hours',
    lectures: 45,
    level: 'Beginner',
    imageId: 'course-thumb-1',
    videoUrl: 'placeholder',
    category: 'Constitutional Law',
    lecturesContent: [
      { title: 'The Making of the Constitution', duration: '15:30' },
      { title: 'Preamble and Its Significance', duration: '20:10' },
      { title: 'Fundamental Rights - Part I', duration: '25:00' },
    ]
  },
  {
    id: '2',
    title: 'Advanced Criminal Law Procedure',
    description: 'Understand the intricacies of the criminal justice system.',
    longDescription: 'This advanced course explores the Code of Criminal Procedure (CrPC) in detail. Topics include FIR, arrest, bail, trial procedures, and appeals. Essential for practicing lawyers and judiciary exam candidates.',
    instructor: 'Adv. Rohan Desai',
    price: 799,
    rating: 4.9,
    reviews: 980,
    duration: '20 hours',
    lectures: 60,
    level: 'Advanced',
    imageId: 'course-thumb-2',
    videoUrl: 'placeholder',
    category: 'Criminal Law',
    lecturesContent: [
      { title: 'Filing an FIR', duration: '18:45' },
      { title: 'Bail Provisions', duration: '22:00' },
      { title: 'Trial Stages', duration: '30:15' },
    ]
  },
  {
    id: '3',
    title: 'Corporate Law and Governance',
    description: 'Navigate the legal landscape of the corporate world.',
    longDescription: 'Learn about the Companies Act, SEBI regulations, and corporate governance best practices. This course is tailored for corporate lawyers, CAs, and business students.',
    instructor: 'Ms. Priya Kapoor',
    price: 699,
    originalPrice: 1299,
    rating: 4.7,
    reviews: 850,
    duration: '18 hours',
    lectures: 55,
    level: 'Intermediate',
    imageId: 'course-thumb-3',
    videoUrl: 'placeholder',
    category: 'Corporate Law',
    lecturesContent: [
      { title: 'Company Incorporation', duration: '20:00' },
      { title: 'Directors\' Duties', duration: '24:30' },
      { title: 'Mergers & Acquisitions', duration: '28:00' },
    ]
  },
  // Add 17 more courses to have at least 20
  {
    id: '4',
    title: 'Intellectual Property Rights',
    description: 'Protecting creations of the mind.',
    longDescription: 'A comprehensive guide to patents, trademarks, copyrights, and trade secrets. Understand the process of registration and litigation in IPR.',
    instructor: 'Dr. Sameer Khan',
    price: 599,
    rating: 4.6,
    reviews: 720,
    duration: '15 hours',
    lectures: 50,
    level: 'Intermediate',
    imageId: 'course-thumb-4',
    videoUrl: 'placeholder',
    category: 'IPR',
    lecturesContent: [
      { title: 'Introduction to IPR', duration: '15:00' },
      { title: 'Trademark Registration', duration: '21:00' },
      { title: 'Copyright Infringement', duration: '23:45' },
    ]
  },
  {
    id: '5',
    title: 'Law of Torts & Consumer Protection',
    description: 'Understanding civil wrongs and consumer rights.',
    longDescription: 'This course covers the principles of tortious liability, negligence, defamation, and the framework of consumer protection in India.',
    instructor: 'Prof. Meera Iyer',
    price: 399,
    originalPrice: 799,
    rating: 4.8,
    reviews: 1100,
    duration: '10 hours',
    lectures: 35,
    level: 'Beginner',
    imageId: 'course-thumb-5',
    videoUrl: 'placeholder',
    category: 'Civil Law',
    lecturesContent: [
        { title: 'What is a Tort?', duration: '12:00' },
        { title: 'Negligence Explained', duration: '18:20' },
        { title: 'Consumer Rights Act', duration: '20:00' },
    ]
  },
  {
    id: '6',
    title: 'Environmental Law & Policy',
    description: 'Legal frameworks for protecting our planet.',
    longDescription: 'Explore national and international environmental laws, including pollution control, wildlife protection, and climate change policies.',
    instructor: 'Adv. Sunita Rao',
    price: 649,
    rating: 4.7,
    reviews: 650,
    duration: '16 hours',
    lectures: 48,
    level: 'Intermediate',
    imageId: 'course-thumb-6',
    videoUrl: 'placeholder',
    category: 'Environmental Law',
     lecturesContent: [
      { title: 'Air & Water Acts', duration: '22:15' },
      { title: 'Wildlife Protection Act', duration: '25:00' },
      { title: 'NGT and its Powers', duration: '21:50' },
    ]
  },
   {
    id: '7',
    title: 'Introduction to Cyber Law',
    description: 'Legal issues in the digital age.',
    longDescription: 'A course on the Information Technology Act, 2000, covering cyber crimes, data protection, and electronic evidence.',
    instructor: 'Mr. Arjun Bala',
    price: 599,
    originalPrice: 1199,
    rating: 4.9,
    reviews: 1500,
    duration: '14 hours',
    lectures: 40,
    level: 'Intermediate',
    imageId: 'course-thumb-7',
    videoUrl: 'placeholder',
    category: 'Cyber Law',
     lecturesContent: [
      { title: 'Digital Signatures', duration: '19:00' },
      { title: 'Data Privacy Laws', duration: '26:00' },
      { title: 'Handling Cyber Crimes', duration: '24:00' },
    ]
  },
  {
    id: '8',
    title: 'Family Law: Marriage & Divorce',
    description: 'A deep dive into personal laws in India.',
    longDescription: 'Learn about the legal aspects of marriage, divorce, maintenance, and adoption under various personal laws in India.',
    instructor: 'Prof. Fatima Sheikh',
    price: 499,
    rating: 4.8,
    reviews: 900,
    duration: '13 hours',
    lectures: 42,
    level: 'Beginner',
    imageId: 'course-thumb-8',
    videoUrl: 'placeholder',
    category: 'Family Law',
     lecturesContent: [
      { title: 'Hindu Marriage Act', duration: '25:30' },
      { title: 'Special Marriage Act', duration: '21:10' },
      { title: 'Divorce Procedures', duration: '28:00' },
    ]
  },
  {
    id: '9',
    title: 'Arbitration and Conciliation',
    description: 'Mastering Alternative Dispute Resolution.',
    longDescription: 'An expert-led course on the Arbitration and Conciliation Act, 1996. Covers domestic and international arbitration.',
    instructor: 'Mr. Vikram Sethi',
    price: 899,
    rating: 4.9,
    reviews: 750,
    duration: '22 hours',
    lectures: 65,
    level: 'Advanced',
    imageId: 'course-thumb-9',
    videoUrl: 'placeholder',
    category: 'ADR',
     lecturesContent: [
      { title: 'Arbitration Agreements', duration: '24:00' },
      { title: 'Conduct of Proceedings', duration: '30:00' },
      { title: 'Enforcement of Awards', duration: '28:45' },
    ]
  },
  {
    id: '10',
    title: 'The Law of Evidence',
    description: 'Principles of evidence admissibility in court.',
    longDescription: 'A critical course for litigators on the Indian Evidence Act, 1872, including relevance, admissibility, and examination of witnesses.',
    instructor: 'Adv. Prakash Jha',
    price: 699,
    originalPrice: 1399,
    rating: 4.8,
    reviews: 1300,
    duration: '19 hours',
    lectures: 58,
    level: 'Intermediate',
    imageId: 'course-thumb-10',
    videoUrl: 'placeholder',
    category: 'Litigation',
     lecturesContent: [
      { title: 'Relevancy of Facts', duration: '23:00' },
      { title: 'Documentary Evidence', duration: '26:30' },
      { title: 'Examination of Witnesses', duration: '29:00' },
    ]
  },
    {
    id: '11',
    title: 'Administrative Law',
    description: 'Checks and balances on government power.',
    longDescription: 'Learn about the principles of administrative law, including judicial review of administrative actions, delegated legislation, and the role of tribunals.',
    instructor: 'Dr. Leela Menon',
    price: 549,
    rating: 4.7,
    reviews: 820,
    duration: '14 hours',
    lectures: 45,
    level: 'Intermediate',
    imageId: 'course-thumb-11',
    videoUrl: 'placeholder',
    category: 'Constitutional Law',
     lecturesContent: [
      { title: 'Principles of Natural Justice', duration: '21:00' },
      { title: 'Writ Jurisdiction', duration: '24:15' },
      { title: 'Ombudsman and Lokpal', duration: '19:40' },
    ]
  },
  {
    id: '12',
    title: 'Taxation Law: GST',
    description: 'Decoding the Goods and Services Tax regime.',
    longDescription: 'A practical guide to GST, covering registration, compliance, input tax credit, and return filing. Essential for CAs and tax professionals.',
    instructor: 'CA Sneha Gupta',
    price: 749,
    originalPrice: 1499,
    rating: 4.9,
    reviews: 1150,
    duration: '18 hours',
    lectures: 55,
    level: 'Advanced',
    imageId: 'course-thumb-12',
    videoUrl: 'placeholder',
    category: 'Taxation Law',
     lecturesContent: [
      { title: 'GST Framework', duration: '20:00' },
      { title: 'Input Tax Credit', duration: '25:30' },
      { title: 'E-Way Bill System', duration: '22:00' },
    ]
  },
  {
    id: '13',
    title: 'Labour Law & Industrial Relations',
    description: 'Rights and obligations in the workplace.',
    longDescription: 'This course covers the new labour codes, including regulations on wages, social security, industrial relations, and occupational safety.',
    instructor: 'Adv. Tarun Singh',
    price: 600,
    rating: 4.6,
    reviews: 780,
    duration: '16 hours',
    lectures: 50,
    level: 'Intermediate',
    imageId: 'course-thumb-13',
    videoUrl: 'placeholder',
    category: 'Labour Law',
     lecturesContent: [
      { title: 'The Wage Code', duration: '23:00' },
      { title: 'Industrial Relations Code', duration: '27:00' },
      { title: 'Social Security Code', duration: '24:45' },
    ]
  },
  {
    id: '14',
    title: 'Human Rights Law & Practice',
    description: 'Championing human dignity and rights.',
    longDescription: 'An in-depth study of the Universal Declaration of Human Rights, the Indian legal framework, and the role of the NHRC.',
    instructor: 'Dr. Kabir Anand',
    price: 550,
    originalPrice: 1100,
    rating: 4.8,
    reviews: 950,
    duration: '12 hours',
    lectures: 40,
    level: 'Beginner',
    imageId: 'course-thumb-14',
    videoUrl: 'placeholder',
    category: 'Human Rights',
     lecturesContent: [
      { title: 'UDHR and Covenants', duration: '20:00' },
      { title: 'Human Rights in India', duration: '25:00' },
      { title: 'Role of NHRC', duration: '22:30' },
    ]
  },
  {
    id: '15',
    title: 'Interpretation of Statutes',
    description: 'The art and science of reading the law.',
    longDescription: 'Learn the rules and principles of statutory interpretation, including literal, golden, and mischief rules, and various aids to interpretation.',
    instructor: 'Justice (Retd.) R.S. Sodhi',
    price: 850,
    rating: 4.9,
    reviews: 1050,
    duration: '15 hours',
    lectures: 45,
    level: 'Advanced',
    imageId: 'course-thumb-15',
    videoUrl: 'placeholder',
    category: 'Jurisprudence',
     lecturesContent: [
      { title: 'Literal Rule', duration: '20:00' },
      { title: 'Golden Rule', duration: '18:50' },
      { title: 'Aids to Interpretation', duration: '24:00' },
    ]
  },
  {
    id: '16',
    title: 'Banking and Insurance Law',
    description: 'Legal aspects of financial services.',
    longDescription: 'This course covers the legal framework governing banks and insurance companies in India, including RBI regulations and the IRDA Act.',
    instructor: 'Mr. Alok Verma',
    price: 650,
    rating: 4.7,
    reviews: 700,
    duration: '17 hours',
    lectures: 52,
    level: 'Intermediate',
    imageId: 'course-thumb-16',
    videoUrl: 'placeholder',
    category: 'Financial Law',
     lecturesContent: [
      { title: 'RBI Act, 1934', duration: '25:00' },
      { title: 'Negotiable Instruments', duration: '28:10' },
      { title: 'Insurance Contracts', duration: '26:00' },
    ]
  },
  {
    id: '17',
    title: 'Competition Law',
    description: 'Promoting fair competition in the market.',
    longDescription: 'An overview of the Competition Act, 2002, focusing on anti-competitive agreements, abuse of dominant position, and regulation of combinations.',
    instructor: 'Ms. Ishita Jain',
    price: 700,
    originalPrice: 1400,
    rating: 4.8,
    reviews: 880,
    duration: '16 hours',
    lectures: 48,
    level: 'Advanced',
    imageId: 'course-thumb-17',
    videoUrl: 'placeholder',
    category: 'Corporate Law',
     lecturesContent: [
      { title: 'Anti-Competitive Agreements', duration: '24:30' },
      { title: 'Abuse of Dominance', duration: '27:00' },
      { title: 'Merger Control', duration: '25:45' },
    ]
  },
  {
    id: '18',
    title: 'Law of Contracts',
    description: 'The building blocks of all legal agreements.',
    longDescription: 'A fundamental course on the Indian Contract Act, 1872. Learn about offer, acceptance, consideration, breach, and remedies.',
    instructor: 'Prof. Anjali Mehta',
    price: 350,
    rating: 4.9,
    reviews: 2500,
    duration: '11 hours',
    lectures: 38,
    level: 'Beginner',
    imageId: 'course-thumb-18',
    videoUrl: 'placeholder',
    category: 'Civil Law',
     lecturesContent: [
      { title: 'Elements of a Contract', duration: '18:00' },
      { title: 'Void and Voidable Contracts', duration: '22:30' },
      { title: 'Remedies for Breach', duration: '20:00' },
    ]
  },
  {
    id: '19',
    title: 'Insolvency and Bankruptcy Code',
    description: 'Understanding corporate insolvency resolution.',
    longDescription: 'A detailed analysis of the IBC, 2016. The course covers the insolvency resolution process for corporates, individuals, and partnership firms.',
    instructor: 'Adv. Karan Thapar',
    price: 950,
    rating: 4.9,
    reviews: 920,
    duration: '25 hours',
    lectures: 70,
    level: 'Advanced',
    imageId: 'course-thumb-19',
    videoUrl: 'placeholder',
    category: 'Corporate Law',
     lecturesContent: [
      { title: 'CIRP Process', duration: '30:00' },
      { title: 'Role of Resolution Professional', duration: '28:00' },
      { title: 'Liquidation Process', duration: '32:15' },
    ]
  },
  {
    id: '20',
    title: 'Public International Law',
    description: 'The law governing relations between States.',
    longDescription: 'Explore the sources of international law, the law of treaties, state jurisdiction, and the role of the International Court of Justice.',
    instructor: 'Dr. Elena Petrova',
    price: 750,
    originalPrice: 1500,
    rating: 4.8,
    reviews: 800,
    duration: '20 hours',
    lectures: 60,
    level: 'Intermediate',
    imageId: 'course-thumb-20',
    videoUrl: 'placeholder',
    category: 'International Law',
     lecturesContent: [
      { title: 'Sources of Int\'l Law', duration: '25:00' },
      { title: 'State Recognition', duration: '22:45' },
      { title: 'The Law of the Sea', duration: '28:00' },
    ]
  }
];
